# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eastman's BlogğŸ€
brief-intro: The grass is no more greener on the other side. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://45.78.51.215" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# VPS configuration
# Follow settings are for deploying the blog to VPS. Used by the deployment shell scripts.
# The client public key should be placed in the .ssh/authorized_keys for connection establishment.
#   vps_htdocs_root - the hyper text document root of the web server in the VPS
vps_host:         eastmanjian.cn
vps_ssh_port:     28411
vps_ssh_username: eastman
vps_htdocs_root:  /srv/www/htdocs
vps_jekyll_site:  /home/eastman/eastman_blog


# other links
twitter_username: 18_50935
facebook_username: eastman.jian
github_username:  EastmanJian
email: 50935@qq.com
weibo_username: jianym@hotmail.com
zhihu_username: 13631342825
linkedIn_username: eastman-jian-0818129b
dribbble_username:

description_footer: I'm loved when I'm completely by myself alone. ç²¤ICPå¤‡17065020å·. 

# comments
# three ways to comment, only choose one, put your comment system configurations here.
duoshuo_shortname: #hygblog
disqus_shortname: #eastmanjian
changyan_appid: cyt67wD0b
changyan_appkey: prod_2ae49e77a11e91f985e24b8cc1ed5a58

# Reward 
# put the 2D barcode image url below.
reward_words: "Thanks for your reward! å¦‚æœè§‰å¾—æˆ‘çš„æ–‡ç« å¯¹æ‚¨æœ‰ç”¨ï¼Œè¯·éšæ„æ‰“èµã€‚æ‚¨çš„æ”¯æŒå°†é¼“åŠ±æˆ‘ç»§ç»­åˆ›ä½œï¼"
alipay_barcode: "https://ejres-1253687085.picgz.myqcloud.com/img/barcode/alipay_s.jpg"
wechat_barcode: "https://ejres-1253687085.picgz.myqcloud.com/img/barcode/wechat_s.png"

# Site Search
# Support Baidu ç«™å†…æœç´¢, input the sid below (you can get the sid from the site search script after you registered baidu ç«™å†…æœç´¢)
baidu_znsv_sid: #10213920283290971852

# statistic analysis ç»Ÿè®¡ä»£ç 
# ç™¾åº¦ç»Ÿè®¡ idï¼Œå°†ç»Ÿè®¡ä»£ç æ›¿æ¢ä¸ºè‡ªå·±çš„ç™¾åº¦ç»Ÿè®¡idï¼Œå³
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxxå­—ç¬¦ä¸²
baidu_tongji_id: 0998a317ab8f322056573eabdaade12c
google_analytics_id: #google åˆ†æè¿½è¸ªid

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

# Handling Reading
exclude:              ["resources/", "cos_sync/", "deploy_github.sh", "deploy_vps.sh", "push_baidu.sh", "sync_src_to_vps.sh"]
